### ISSUE TITLE
Unable to add testCaseId, IssueId etc

### ISSUE THREAD

**Issue by hemanthsridhar** [kirlionik/allure-cucumber-plugin#1]
Dear Anton,

Thank you so much for this plugin.

I need your help. Can you please clone https://github.com/hemanthsridhar/CucumberJVM-Junit-TestSetUp.git and tell me what mistake I have done for the attachments to not be available in the report? I am not able to get testcaseid, issueid etc.

Thank you so much in advance.

**Comment by gvvinblade** [comment]
Hi Hemanth Sridhar!

The first issue I see in your code is using cucumber-jvm-adapter. The plugin is replacement for it and doesn't require it at all. It's possible to get some conflicts mixing them together

**Comment by hemanthsridhar** [comment]
@gvvinblade you are right. Thank you so much. But how am I going to capture a screenshot and attach it to allure **when the test fails** if I cannot extends AllureRunListner and override the  testFailure(Failure failure) method?

Please find below for the link where in I had a question regarding the same using cucumber-jvm-adaptor.
https://github.com/allure-framework/allure-cucumber-jvm-adaptor/issues/33

**Comment by gvvinblade** [comment]
You don't need the listener to make annotations work. As allure works with annotations and aspects, you're able to do it inside any listener - just implement your own and override the method. But i think it goes against the cucumber ideology.. I'll think about probable better solution and will let you now how to do it beautifully)

**Comment by hemanthsridhar** [comment]
@gvvinblade alright thank you. :).

But I think you did not understand my question. 

Since I am using AllureRunListner from jvm adaptor and you used it causes problems if I use jvm adaptor, what I do to capture a screenshot and attach it to the allure report.

Hope you understood my question.

**Comment by kirlionik** [comment]
@hemanthsridhar Hello. I am sorry for delay in answer. I understand your questions. In your case i could create your custom listener and add call attachment method into listener. I do not need to override or customize cucumber plugin. 
If you will have a questions you could ping me at skype: shapin_anton. I will be happy to help you.

**Comment by hemanthsridhar** [comment]
@kirlionik
Hi thank you for your reply. Could you please add an example on how attach a screenshot when the scenario fails It would be great.

Thank you in advance
