### ISSUE TITLE
Unable to add multiple test case IDs

### ISSUE THREAD

**Issue by hemanthsridhar** [kirlionik/allure-cucumber-plugin#2]
Dear Anton,

I am not able to add multiple test case IDs for Scenarios. This is required and makes more sense when you use Scenario Outline.

Eg:  @attachment @SeverityLevel.BLOCKER @TestCaseId("TC_001") @TestCaseId("TC_002")
  Scenario Outline: sample attachment tests
    Given I am in Home Page
    And I attach "<fileformat>" files

    Examples: 
      | fileformat |
      | xlsx       |
      | csv        |
      | txt        |

Please consider this as an enhancement.

Thank you in advance.

**Comment by gvvinblade** [comment]
@hemanthsridhar Sorry for late reply. It's an internal Allure limitation. It should have an unique case Id and the Allure @TestCaseId java annotation (in which the plugin transforms a particular tag) isn't repeatable. So, we cannot use multiple @TestCaseId tag on a scenario

Probably @Issue tag can help you in such case... You're able to use them as many as you need

**Comment by hemanthsridhar** [comment]
@gvvinblade  thanks for the suggestion :) makes sense
